version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "12:00"
      timezone: "Europe/Moscow"
  - package-ecosystem: "npm"
    directory: "/js"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "12:00"
      timezone: "Europe/Moscow"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
  - package-ecosystem: "bundler"
    directory: "/ruby"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "12:00"
      timezone: "Europe/Moscow"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
  - package-ecosystem: "pip"
    directory: "/python"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "12:00"
      timezone: "Europe/Moscow"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
