version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "12:00"
      timezone: "Europe/Moscow"
  - package-ecosystem: "npm"
    directory: "/js"
    schedule:
      interval: "daily"
      time: "12:00"
      timezone: "Europe/Moscow"
  - package-ecosystem: "bundler"
    directory: "/ruby"
    schedule:
      interval: "daily"
      time: "12:00"
      timezone: "Europe/Moscow"
  - package-ecosystem: "pip"
    directory: "/python"
    schedule:
      interval: "daily"
      time: "12:00"
      timezone: "Europe/Moscow"
