name: Dependabot-Test

on:
  push:
    branches:
      - master

jobs:
  dependabot-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.5

      - name: Set up Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: "3.10"

      - name: Set up Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: "20"

      - name: Set up Java
        uses: actions/setup-java@v4.2.1
        with:
          distribution: "zulu"
          java-version: "20"
          architecture: "x64"
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1.176.0
        with:
          ruby-version: "3.0"

      - name: Install Qt
        uses: jurplel/install-qt-action@v3.3.0
        with:
          version: "6.7.0"
          host: "linux"
          target: "desktop"
          install-deps: "true"
          cache: "false"
  
  js:
    runs-on: ubuntu-latest
    steps:
      - name: Git Clone
        uses: actions/checkout@v4.1.5

      - name: Set up Node.js
        uses: actions/setup-node@v4.0.2
        with:
          node-version: "20"

      - name: Install
        run: |
          cd js
          npm install
  
  ruby:
    runs-on: ubuntu-latest
    steps:
      - name: Git Clone
        uses: actions/checkout@v4.1.5

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1.176.0
        with:
          ruby-version: "3.0"

      - name: Install
        run: |
          cd ruby
          gem install bundler
          bundle install

  python:
    runs-on: ubuntu-latest
    steps:
      - name: Git Clone
        uses: actions/checkout@v4.1.5

      - name: Set up Python
        uses: actions/setup-python@v5.1.0
        with:
          python-version: "3.10"

      - name: Install
        run: |
          cd python
          python -m pip install --upgrade pip
          pip install -r requirements.txt